name: tests

on:
  push:
  pull_request:

jobs:
  unittest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - run: python3 --version
      - run: python3 -m unittest discover -s tests -v
